# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = 

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = 

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /CMakeFiles //CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blockchain

# Build rule for target.
blockchain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blockchain
.PHONY : blockchain

# fast build rule for target.
blockchain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/build
.PHONY : blockchain/fast

src/blockchain/CBlock.o: src/blockchain/CBlock.cpp.o
.PHONY : src/blockchain/CBlock.o

# target to build an object file
src/blockchain/CBlock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CBlock.cpp.o
.PHONY : src/blockchain/CBlock.cpp.o

src/blockchain/CBlock.i: src/blockchain/CBlock.cpp.i
.PHONY : src/blockchain/CBlock.i

# target to preprocess a source file
src/blockchain/CBlock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CBlock.cpp.i
.PHONY : src/blockchain/CBlock.cpp.i

src/blockchain/CBlock.s: src/blockchain/CBlock.cpp.s
.PHONY : src/blockchain/CBlock.s

# target to generate assembly for a file
src/blockchain/CBlock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CBlock.cpp.s
.PHONY : src/blockchain/CBlock.cpp.s

src/blockchain/CChain.o: src/blockchain/CChain.cpp.o
.PHONY : src/blockchain/CChain.o

# target to build an object file
src/blockchain/CChain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CChain.cpp.o
.PHONY : src/blockchain/CChain.cpp.o

src/blockchain/CChain.i: src/blockchain/CChain.cpp.i
.PHONY : src/blockchain/CChain.i

# target to preprocess a source file
src/blockchain/CChain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CChain.cpp.i
.PHONY : src/blockchain/CChain.cpp.i

src/blockchain/CChain.s: src/blockchain/CChain.cpp.s
.PHONY : src/blockchain/CChain.s

# target to generate assembly for a file
src/blockchain/CChain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CChain.cpp.s
.PHONY : src/blockchain/CChain.cpp.s

src/blockchain/CLog.o: src/blockchain/CLog.cpp.o
.PHONY : src/blockchain/CLog.o

# target to build an object file
src/blockchain/CLog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CLog.cpp.o
.PHONY : src/blockchain/CLog.cpp.o

src/blockchain/CLog.i: src/blockchain/CLog.cpp.i
.PHONY : src/blockchain/CLog.i

# target to preprocess a source file
src/blockchain/CLog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CLog.cpp.i
.PHONY : src/blockchain/CLog.cpp.i

src/blockchain/CLog.s: src/blockchain/CLog.cpp.s
.PHONY : src/blockchain/CLog.s

# target to generate assembly for a file
src/blockchain/CLog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/CLog.cpp.s
.PHONY : src/blockchain/CLog.cpp.s

src/blockchain/net/CClient.o: src/blockchain/net/CClient.cpp.o
.PHONY : src/blockchain/net/CClient.o

# target to build an object file
src/blockchain/net/CClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/CClient.cpp.o
.PHONY : src/blockchain/net/CClient.cpp.o

src/blockchain/net/CClient.i: src/blockchain/net/CClient.cpp.i
.PHONY : src/blockchain/net/CClient.i

# target to preprocess a source file
src/blockchain/net/CClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/CClient.cpp.i
.PHONY : src/blockchain/net/CClient.cpp.i

src/blockchain/net/CClient.s: src/blockchain/net/CClient.cpp.s
.PHONY : src/blockchain/net/CClient.s

# target to generate assembly for a file
src/blockchain/net/CClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/CClient.cpp.s
.PHONY : src/blockchain/net/CClient.cpp.s

src/blockchain/net/CServer.o: src/blockchain/net/CServer.cpp.o
.PHONY : src/blockchain/net/CServer.o

# target to build an object file
src/blockchain/net/CServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/CServer.cpp.o
.PHONY : src/blockchain/net/CServer.cpp.o

src/blockchain/net/CServer.i: src/blockchain/net/CServer.cpp.i
.PHONY : src/blockchain/net/CServer.i

# target to preprocess a source file
src/blockchain/net/CServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/CServer.cpp.i
.PHONY : src/blockchain/net/CServer.cpp.i

src/blockchain/net/CServer.s: src/blockchain/net/CServer.cpp.s
.PHONY : src/blockchain/net/CServer.s

# target to generate assembly for a file
src/blockchain/net/CServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/CServer.cpp.s
.PHONY : src/blockchain/net/CServer.cpp.s

src/blockchain/net/INet.o: src/blockchain/net/INet.cpp.o
.PHONY : src/blockchain/net/INet.o

# target to build an object file
src/blockchain/net/INet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/INet.cpp.o
.PHONY : src/blockchain/net/INet.cpp.o

src/blockchain/net/INet.i: src/blockchain/net/INet.cpp.i
.PHONY : src/blockchain/net/INet.i

# target to preprocess a source file
src/blockchain/net/INet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/INet.cpp.i
.PHONY : src/blockchain/net/INet.cpp.i

src/blockchain/net/INet.s: src/blockchain/net/INet.cpp.s
.PHONY : src/blockchain/net/INet.s

# target to generate assembly for a file
src/blockchain/net/INet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/net/INet.cpp.s
.PHONY : src/blockchain/net/INet.cpp.s

src/blockchain/storage/CStorageLocal.o: src/blockchain/storage/CStorageLocal.cpp.o
.PHONY : src/blockchain/storage/CStorageLocal.o

# target to build an object file
src/blockchain/storage/CStorageLocal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/storage/CStorageLocal.cpp.o
.PHONY : src/blockchain/storage/CStorageLocal.cpp.o

src/blockchain/storage/CStorageLocal.i: src/blockchain/storage/CStorageLocal.cpp.i
.PHONY : src/blockchain/storage/CStorageLocal.i

# target to preprocess a source file
src/blockchain/storage/CStorageLocal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/storage/CStorageLocal.cpp.i
.PHONY : src/blockchain/storage/CStorageLocal.cpp.i

src/blockchain/storage/CStorageLocal.s: src/blockchain/storage/CStorageLocal.cpp.s
.PHONY : src/blockchain/storage/CStorageLocal.s

# target to generate assembly for a file
src/blockchain/storage/CStorageLocal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/storage/CStorageLocal.cpp.s
.PHONY : src/blockchain/storage/CStorageLocal.cpp.s

src/blockchain/storage/storage.o: src/blockchain/storage/storage.cpp.o
.PHONY : src/blockchain/storage/storage.o

# target to build an object file
src/blockchain/storage/storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/storage/storage.cpp.o
.PHONY : src/blockchain/storage/storage.cpp.o

src/blockchain/storage/storage.i: src/blockchain/storage/storage.cpp.i
.PHONY : src/blockchain/storage/storage.i

# target to preprocess a source file
src/blockchain/storage/storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/storage/storage.cpp.i
.PHONY : src/blockchain/storage/storage.cpp.i

src/blockchain/storage/storage.s: src/blockchain/storage/storage.cpp.s
.PHONY : src/blockchain/storage/storage.s

# target to generate assembly for a file
src/blockchain/storage/storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/blockchain/storage/storage.cpp.s
.PHONY : src/blockchain/storage/storage.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... blockchain"
	@echo "... src/blockchain/CBlock.o"
	@echo "... src/blockchain/CBlock.i"
	@echo "... src/blockchain/CBlock.s"
	@echo "... src/blockchain/CChain.o"
	@echo "... src/blockchain/CChain.i"
	@echo "... src/blockchain/CChain.s"
	@echo "... src/blockchain/CLog.o"
	@echo "... src/blockchain/CLog.i"
	@echo "... src/blockchain/CLog.s"
	@echo "... src/blockchain/net/CClient.o"
	@echo "... src/blockchain/net/CClient.i"
	@echo "... src/blockchain/net/CClient.s"
	@echo "... src/blockchain/net/CServer.o"
	@echo "... src/blockchain/net/CServer.i"
	@echo "... src/blockchain/net/CServer.s"
	@echo "... src/blockchain/net/INet.o"
	@echo "... src/blockchain/net/INet.i"
	@echo "... src/blockchain/net/INet.s"
	@echo "... src/blockchain/storage/CStorageLocal.o"
	@echo "... src/blockchain/storage/CStorageLocal.i"
	@echo "... src/blockchain/storage/CStorageLocal.s"
	@echo "... src/blockchain/storage/storage.o"
	@echo "... src/blockchain/storage/storage.i"
	@echo "... src/blockchain/storage/storage.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

